[wokwi]
version = 1
elf = ".pio/build/lolin_c3_mini/firmware.elf"
firmware = ".pio/build/lolin_c3_mini/firmware.bin"
rfc2217ServerPort = 4000

# Forward http://localhost:8180 to port 80 on the simulated ESP32:
[[net.forward]]
from = "localhost:8180"
to = "target:80"